### ISSUE TITLE
v0.4.0 - feature cortex-m not available

### ISSUE THREAD

**Issue by kolbma** [probe-rs/rtt-target#33]
You have removed the features (e.g. cortex-m) in the new version, but you are checking for with `cfg` in code for it:
https://github.com/probe-rs/rtt-target/blob/4d8bdd8e371f0701595dbfed0b185db188516c2e/rtt-target/src/debug.rs#L26-L30

**Comment by nickmertin** [comment]
I am having this issue as well. Attempting to build a binary against it results in linker errors for undefined symbols `_critical_section_1_0_acquire` and `_critical_section_1_0_release`.
