### ISSUE TITLE
Out-of-date documentation regarding "cortex-m" and "riscv" features

### ISSUE THREAD

**Issue by dlaw** [probe-rs/rtt-target#45]
It appears that the cortex-m and riscv features were removed from this crate, but the documentation still makes reference to them.

https://github.com/probe-rs/rtt-target/blob/a1bae7cb3f6b81834d8f0030546baeabe0331d13/rtt-target/src/lib.rs#L12

which is rendered into https://docs.rs/rtt-target/latest/rtt_target/#hardware-support

Cheers!

**Comment by bugadani** [comment]
Fixed in #49

**Comment by lure23** [comment]
It's still in the [docs via `crates.io`](https://docs.rs/rtt-target/0.5.0/rtt_target/) though, since no further release. (just saying...)
